### ISSUE TITLE
[bug] 在lineageos下无法开启vpn

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#1895]
# 系统环境
- Android 版本 12 SQ3A
- LineageOS 版本 19-20230106-NIGHTLY-haydn

# 录屏

https://nekodisk.top/f/eLCN/screen-20230107-122350.mp4

<video src="https://nekodisk.top/f/eLCN/screen-20230107-122350.mp4"></video>

**Comment by kewtgh** [comment]
The same problem as #1887 & #1893 & #1889.
That's because China Telecom block V2rayng's connection. Other apps are OK. And China Mobile Com. is OK too.
That's not the problem of LineageOS system, Huawei's EMUI still has the same problem.
Maybe V2rayng's connection can be recognized by China Telecom. They adjust the time and make the connection unavailable.

**Comment by kewtgh** [comment]
> The same problem as #1887. That's because China Telecom block V2rayng's connection. Other apps are OK. And China Mobile Com. is OK too. That's not the problem of LineageOS system, Huawei's EMUI still has the same problem. Maybe V2rayng's connection can be recognized by China Telecom. They adjust the time and make the connection unavailable.

This happened since Jan 4th.

**Comment by kewtgh** [comment]
Change to other apps, or use China Mobile Com. can solve the problem.

**Comment by Larpx** [comment]
我的手机是小米13p，miui14
我和你遇到通往的情况了，然后解决了，我是这么做的，建议你也试试看：
1.应用设置里删除该app所有数据，
2.查是否允许该app发送通知（必须允许），或者在首次运行时弹出的是否允许通知时选择始终允许

**Comment by yogkin** [comment]
Check to see if the system time is correct

**Comment by kewtgh** [comment]
My problem was solved after I updated my app to version [1.7.35]. 
Before that I use another app as a replacement.
