### ISSUE TITLE
Feature suggestion - Automatic update of subscription, and, once utls settings for all configs

### ISSUE THREAD

**Issue by MrVb0** [2dust/v2rayNG#1910]
Hello, thank you for your great application. I have two practical suggestions:
- Please make it so that the subscription is automatically updated by default.
- Please consider settings that can change all utls configurations at once.

**Comment by donnyxray** [comment]
To comment on automatic updating: it seems many apps update the list at a set or configurable interval. It is user-controlled. This is sub-optimal, because the user does not know the planned/expected lifetime of a server.

IMHO a better approach would be to give the subscription (or maybe each server) an expire time. That way the provider can ensure servers are removed from the list when their planned/expected lifetime is over.

**Comment by omid1980** [comment]
Please add an Auto update to the Subscription

**Comment by MrVb0** [comment]
It is also good if you set utls to randomized by default, and enable allow insecure by default

**Comment by sbh96** [comment]
Please  add support `profile-update-interval` subscription response header to read auto update interval from response and enable auto update in subscription group if this header exist
@2dust 
This header future is common in hiddify and v2box and Streisand and other v2ray apps so you most add this option in v2rayng
