### ISSUE TITLE
不能进去Chatgpt 1020错误

### ISSUE THREAD

**Issue by cs328yy** [2dust/v2rayNG#2140]
Access denied
You do not have access to chat.openai.com.

The site owner may have set restrictions that prevent you from accessing the site.

Ray ID: 7af546c50a5e19d2
Timestamp: 2023-03-29 04:12:46 UTC
Your IP address: 13.208.166.62
Requested URL: chat.openai.com/
Error reference number: 1020
Server ID: FL_594F13
User-Agent: Mozilla/5.0 (Linux; Android 12; HarmonyOS; ELS-AN00; HMSCore 6.9.6.302) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.88 HuaweiBrowser/13.0.4.302 Mobile Safari/537.36

**Comment by lizina66** [comment]
笑死，自己ip问题跑来问软件

**Comment by SkywalkerDarren** [comment]
同样的问题，梯子套了warp后，在pc上使用xray或openwrt上使用passwall可正常访问，手机在openwrt上也可正常访问。但只要切换到v2rayng就无法正常访问，而且奇怪的是在ifconfig.me上测试则首次显示的是warp的ip地址，再次刷新就会变成原地址。进一步测试还发现这个情况只会在ws+vless的情况下会出现？当我切换到xtls+vless时就不会有这样的问题了。
PS：pc上的xray和openwrt上用的ws+vless是没有这样的问题的。

**Comment by yxxyun** [comment]
我也是碰到同样问题，套了warp后，电脑，iOS端都没问题，ng就无法正常访问。

**Comment by Webpage-gh** [comment]
看起来像是IP问题。[Google](https://www.google.com)正常吗

**Comment by SkywalkerDarren** [comment]
> 看起来像是IP问题。[Google](https://www.google.com)正常吗

不像是服务器问题，因为在相同协议的情况下pc上的xray和openwrt上的passwall都是正常访问的，而在手机端只挂v2rayng的情况下才会出现异常。

**Comment by LynxZeta** [comment]
> 同样的问题，梯子套了warp后，在pc上使用xray或openwrt上使用passwall可正常访问，手机在openwrt上也可正常访问。但只要切换到v2rayng就无法正常访问，而且奇怪的是在ifconfig.me上测试则首次显示的是warp的ip地址，再次刷新就会变成原地址。进一步测试还发现这个情况只会在ws+vless的情况下会出现？当我切换到xtls+vless时就不会有这样的问题了。 PS：pc上的xray和openwrt上用的ws+vless是没有这样的问题的。

I ran into the same issue as you. When I was using Passwall on OpenWrt, from any device, everything seemed to be working just fine. But when I switched over to V2rayNG on my phone, the WARP on the server didn't seem to be doing its job properly, and I kept getting the  annoying 1020 error message with the original IP address. 

I've seen other people with similar problems.
https://silentming.net/blog/2023/03/27/using-cfwraper/
https://91ai.net/thread-1150216-1-1.html

After testing things out on a few different phones, I discovered that certain versions of mobile browsers aren't affected by this issue (Webkit 537.36 / Chrome 92.0.4515.166). So I'm not entirely sure whether this is a V2rayNG bug or if it's being caused by the mobile browsers themselves.

Sorry for Mei You Zhong Wen Shu Ru Fa.

**Comment by Orochi-Adde** [comment]
遇到相同bug,v2rayng会泄露给已被warp代理网址真实vps ip,版本1.7.38（1000....）

**Comment by Orochi-Adde** [comment]
安卓12，MIUI13,天玑8100,百分百触发此bug，使用sagerNet可修复

**Comment by Orochi-Adde** [comment]
[v2rayNG_1.7.38_armeabi-v7a.apk](https://github.com/2dust/v2rayNG/releases/download/1.7.38/v2rayNG_1.7.38_armeabi-v7a.apk)
此版本百分百可触发，vps连接warp后仍泄露真实ip给目标服务器

**Comment by zhuzf88** [comment]
两台安卓都有此问题，iphone没问题，都是最新版chrome

**Comment by ridewindx** [comment]
v2rayNG 设置中的 VPN DNS 和远程 DNS 都不要用默认的 1.1.1.1，可以使用其他 DNS，比如 dns.google

**Comment by zuilintan** [comment]
> 笑死，自己ip问题跑来问软件

看到这么多人踩你, 我就放心了
