### ISSUE TITLE
AllowInsecure=1 option is not parsed when Importing configs or updating subscriptions

### ISSUE THREAD

**Issue by farid220** [2dust/v2rayNG#2626]
AllowInsecure=1 is not parsed when importing configs or receiving it via subscription URL.
In some configurations we deliberately set AllowInsecure to True to bypass censorship. But importing it using a vless/vmess link doesn't work because &AllowInsecure is not processed when importing it in V2RayNG.

This is a serious problem for some people to edit it manually so I'd be grateful if you could fix it.

I understand you might be concerned with the security perspectives of this "&AllowInsecure=1" so I recommend displaying a warning so user can interactively choose to allow it or not. This is much easier than telling them to change it manually.

BTW, Thanks for this new Auto Update feature.

**Comment by srvh** [comment]
I see that this Issue was closed as completed by 2dust on Nov 21, 2023
But I still can not use function AllowInsecure=1  in auto update sunscription.
Please, allow use this feature for auto update subscriptions.
I tried to setup AllowInsecure in General Settings, but connection is not working well. I still need to make AllowInsecure=true for all connections manually. I have more than 30 connections. And when I want to update subscription, then I need to make AllowInsecure=true for each connections manually.

**Comment by hossein-mohseni** [comment]
same problem
