### ISSUE TITLE
The latest version of mobile Android v2rayNg fails to start the service with splithttp h3

### ISSUE THREAD

**Issue by dantesieg** [2dust/v2rayNG#3344]
When trying to start using splithttp h3 proxy, v2rayng crashes and tries to connect again.

**Comment by ghost** [comment]
> When trying to start using splithttp h3 proxy, v2rayng crashes and tries to connect again.

Yes , It doesn't work with alpn http/1.1 or h3 !

**Comment by kirito201711** [comment]
+1，同样遇到这个问题

**Comment by yuhan6665** [comment]
哪位上传一下日志。。

**Comment by mmmray** [comment]
@yuhan6665 https://github.com/XTLS/Xray-core/pull/3559

https://github.com/XTLS/Xray-core/issues/3556 I think it's the same bug but not 100% sure.

I am trying to compile v2rayNG so I can verify they actually fix the issue, but am getting stuck because libv2ray is built, but gradle can't find it. The issue should be reproducible with any splithttp h3 config. If you can verify it then I think it's ok to merge and release Xray @RPRX

**Comment by mmmray** [comment]
Nevermind figured it out: https://github.com/XTLS/Xray-core/pull/3554#issuecomment-2239725683
