### ISSUE TITLE
v2rayNG 泄露WEBRTC IP问题

### ISSUE THREAD

**Issue by sdo888999** [2dust/v2rayNG#4021]
使用v2rayN 登陆检测网站 IP8.com 是不会出现检测泄露WEBRTC 问题
![16-12](https://github.com/user-attachments/assets/0cc5eae4-3cfa-4616-bbc7-f164c4f45e39)

v2rayNG 安卓端就有泄露WEBRTC IP问题
![1732338915480](https://github.com/user-attachments/assets/db8a52e4-5634-4169-862c-250ada09e1ef)

发现一个 IP 26.26.26.1 的泄露，这是否是一个识别标志

这个问题应该需要修复

**Comment by deepsm0ke** [comment]
This is because of tun2socks and I think developer should use private IPs instead of 26.26.26.1 when running the command (--netif-ipaddr) to configure tun2socks with v2rayng Like: (IPv4: 10.0.0.1)(IPv6: FD00::1/7) .

![Screenshot_20241123_141850_v2rayNG](https://github.com/user-attachments/assets/10ce4bfd-6cad-4d92-8266-59e4496c82b5)
