### ISSUE TITLE
Hysteria2

### ISSUE THREAD

**Issue by dreamboxone** [2dust/v2rayNG#4100]
Hi. I  use v2rayng v 1.9.24.
I tried to copy and paste a hysteria2, but it says "failed".
Thanks

**Comment by 2dust** [comment]
no config
no log

**Comment by ReturnFI** [comment]
Hello, @2dust 

The config generated by my [script ](https://github.com/ReturnFI/Hysteria2)uses `pinSHA256`, which has a URI example like this:

`
hy2://user:password@IP:PORT?obfs=salamander&obfs-password=password&pinSHA256=sha256/u.....4o=&insecure=1&sni=bts.com
`

The issue is resolved when we remove `pinSHA256` from the config.
However, this parameter is necessary for verify the server's certificate fingerprint.

Thank you.
