### ISSUE TITLE
Add subscription with install-sub intent have issue

### ISSUE THREAD

**Issue by MK0ltra** [2dust/v2rayNG#4141]
When using `v2rayng://install-sub?url=https://sub.jp#SubName` intent to add subscription url, App says `Subscription imported Successfully` But it's not showing any of the configs until i choose `3 dots > Update current group subscription`

This issue is not happening when i copy the subscription url and added with: `+ button > Import config from clipboard`

Expected behavior: When a subscription url is added to app, it should automatically update it and show the configs.
![Screenshot_20241216_103637](https://github.com/user-attachments/assets/8b9a83e1-c16d-4b68-9848-30cfffcf72b0)
Version: 1.9.24

**Comment by 2dust** [comment]
But there is no plan to improve this feature unless someone PRs it

**Comment by Me-verner** [comment]
> But there is no plan to improve this feature unless someone PRs it
@2dust 

It’s been a long time since this section was updated, which might confuse regular users. I suggest adding extra parameters when importing subscriptions through the `install-sub` intent.  

Specifically, after adding a subscription link like `v2rayng://install-sub?url=https://sub.jp#SubName`, the app should:  
1. Automatically update the subscription and load the configurations.  
2. Allow optional parameters (e.g., enabling auto-update) during the import process.  

This would make it much easier for users, as most (90%) prefer simplicity and might not be familiar with manual settings. With one click, the subscription would be added, auto-updated, and ready to use without requiring any further steps.
