### ISSUE TITLE
手机版缺少mux功能导致大量的TCP链接进入服务器引起卡顿，连接数过高

### ISSUE THREAD

**Issue by 1265578519** [2dust/v2rayNG#606]
手机版缺少mux功能导致大量的TCP链接进入服务器引起卡顿，连接数过高
希望加一个mux功能谢谢
抓包看到结果，一大堆tcp链接
![QQ图片20200918174434](https://user-images.githubusercontent.com/6442439/93584773-5c005800-f9d8-11ea-9f1e-f51e6daf5b0d.jpg)

**Comment by 1265578519** [comment]
希望给个全局选项并且默认开启

**Comment by OoHHHHHHH** [comment]
同求！mkcp用户也需要……

**Comment by iKira** [comment]
v2RayNG支持自定义配置，可以自己把mux字段加上去。

**Comment by ghost** [comment]
这个的确可以考虑下，不过默认开启那是不可能的，因为那会导致严重的性能问题。而且也不利于对抗高延迟丢包环境。

**Comment by 1265578519** [comment]
@devinstever 你要知道，如果不开启的话，那么一个页面一两百个请求，就需要建立两百个tcp连接，握手200次，导致tcp握手响应时间严重拖慢速度，并且引起大量的tcp包请求导致性能问题，引起发热，功耗高等现象，并且不止手机客户端，服务器服务端也会导致大量的tcp包拥堵服务器引起死机等问题

**Comment by devinstever** [comment]
并不会发生你提到的现象，我实测了一下，每个页面一两百个请求最多也就十几条连接。再说了，shadowsocks从诞生以来也没有这个特性过，也没见那里报告过与此有关的性能问题。发热和耗电大多数情况下都是因为加密和连接方式的问题（例如websocket的方式就比纯连接耗电多），连接残留的话也不是什么问题，重新开关下对应的网络或者重开关下v2rayng的服务就没了。如果不去管那linux内核也会在超时时间后释放连接的。如果默认开了这个选项的话，会给更多普通用户带来极大的困扰，他们可能会想这软件怎么速度上和单纯的vpn没有区别？然后就会招来更多无意义的问题报告。
 
 
  2020 年 11 月 5 日周四 17:19，小樱<notifications@github.com> 写道：   


@devinstever 你要知道，如果不开启的话，那么一个页面一两百个请求，就需要建立两百个tcp连接，握手200次，导致tcp握手响应时间严重拖慢速度，并且引起大量的tcp包请求导致性能问题，引起发热，功耗高等现象，并且不止手机客户端，服务器服务端也会导致大量的tcp包拥堵服务器引起死机等问题

**Comment by ghost** [comment]
我还真没见过因为连接残留导致死机的，请问你所用的节点vps内存都是128M甚至是64M的超低端机器吗？如果是的话的确可以主动开启这个功能。 
 
  2020 年 11 月 5 日周四 17:19，小樱<notifications@github.com> 写道：   


@devinstever 你要知道，如果不开启的话，那么一个页面一两百个请求，就需要建立两百个tcp连接，握手200次，导致tcp握手响应时间严重拖慢速度，并且引起大量的tcp包请求导致性能问题，引起发热，功耗高等现象，并且不止手机客户端，服务器服务端也会导致大量的tcp包拥堵服务器引起死机等问题

**Comment by 1265578519** [comment]
> 并不会发生你提到的现象，我实测了一下，每个页面一两百个请求最多也就十几条连接。再说了，shadowsocks从诞生以来也没有这个特性过，也没见那里报告过与此有关的性能问题。发热和耗电大多数情况下都是因为加密和连接方式的问题（例如websocket的方式就比纯连接耗电多），连接残留的话也不是什么问题，重新开关下对应的网络或者重开关下v2rayng的服务就没了。如果不去管那linux内核也会在超时时间后释放连接的。如果默认开了这个选项的话，会给更多普通用户带来极大的困扰，他们可能会想这软件怎么速度上和单纯的vpn没有区别？然后就会招来更多无意义的问题报告。 2020 年 11 月 5 日周四 17:19，小樱<notifications@github.com> 写道： @devinstever 你要知道，如果不开启的话，那么一个页面一两百个请求，就需要建立两百个tcp连接，握手200次，导致tcp握手响应时间严重拖慢速度，并且引起大量的tcp包请求导致性能问题，引起发热，功耗高等现象，并且不止手机客户端，服务器服务端也会导致大量的tcp包拥堵服务器引起死机等问题 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

你这个是已经启用了mux，所以才会只有十几个请求连接，或者你访问的页面内容比较少，你可以通过f12抓包看页面具体的请求数量有多少

**Comment by ghost** [comment]
这不应该看那里，而是应该看操作系统，我观察这个现象的方式是在一个root的安卓手机上使用adb shell安装busybox以后使用ss这个命令查看的。我打开了一个bilibili直播页面和一个淘宝页面，最多也就十几条。
等有时间我传个截图上来就明白了。 
 
  2020 年 11 月 5 日周四 17:33，小樱<notifications@github.com> 写道：   



并不会发生你提到的现象，我实测了一下，每个页面一两百个请求最多也就十几条连接。再说了，shadowsocks从诞生以来也没有这个特性过，也没见那里报告过与此有关的性能问题。发热和耗电大多数情况下都是因为加密和连接方式的问题（例如websocket的方式就比纯连接耗电多），连接残留的话也不是什么问题，重新开关下对应的网络或者重开关下v2rayng的服务就没了。如果不去管那linux内核也会在超时时间后释放连接的。如果默认开了这个选项的话，会给更多普通用户带来极大的困扰，他们可能会想这软件怎么速度上和单纯的vpn没有区别？然后就会招来更多无意义的问题报告。 2020 年 11 月 5 日周四 17:19，小樱notifications@github.com 写道： @devinstever 你要知道，如果不开启的话，那么一个页面一两百个请求，就需要建立两百个tcp连接，握手200次，导致tcp握手响应时间严重拖慢速度，并且引起大量的tcp包请求导致性能问题，引起发热，功耗高等现象，并且不止手机客户端，服务器服务端也会导致大量的tcp包拥堵服务器引起死机等问题 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.


你这个是已经启用了mux，所以才会只有十几个请求连接，或者你访问的页面内容比较少，你可以通过f12抓包看页面具体的请求数量有多少

**Comment by 1265578519** [comment]
> 这不应该看那里，而是应该看操作系统，我观察这个现象的方式是在一个root的安卓手机上使用adb shell安装busybox以后使用ss这个命令查看的。我打开了一个bilibili直播页面和一个淘宝页面，最多也就十几条。 等有时间我传个截图上来就明白了。 2020 年 11 月 5 日周四 17:33，小樱<notifications@github.com> 写道： 并不会发生你提到的现象，我实测了一下，每个页面一两百个请求最多也就十几条连接。再说了，shadowsocks从诞生以来也没有这个特性过，也没见那里报告过与此有关的性能问题。发热和耗电大多数情况下都是因为加密和连接方式的问题（例如websocket的方式就比纯连接耗电多），连接残留的话也不是什么问题，重新开关下对应的网络或者重开关下v2rayng的服务就没了。如果不去管那linux内核也会在超时时间后释放连接的。如果默认开了这个选项的话，会给更多普通用户带来极大的困扰，他们可能会想这软件怎么速度上和单纯的vpn没有区别？然后就会招来更多无意义的问题报告。 2020 年 11 月 5 日周四 17:19，小樱notifications@github.com 写道： @devinstever 你要知道，如果不开启的话，那么一个页面一两百个请求，就需要建立两百个tcp连接，握手200次，导致tcp握手响应时间严重拖慢速度，并且引起大量的tcp包请求导致性能问题，引起发热，功耗高等现象，并且不止手机客户端，服务器服务端也会导致大量的tcp包拥堵服务器引起死机等问题 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. 你这个是已经启用了mux，所以才会只有十几个请求连接，或者你访问的页面内容比较少，你可以通过f12抓包看页面具体的请求数量有多少 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

你手机装个终端模拟器用ssh权限执行，不需要root权限没那么麻烦。
或者服务器上用这个命令看一下就知道了
netstat -apn | grep v2ray

**Comment by ghost** [comment]
服务器上看到的并不准确，因为看到的连接总数是 客户端向代理服务程序的连接、代理服务程序向外的连接、服务器其他程序向外的连接加起来的。

发自 Android 版 Yahoo 邮箱 
 
  2020 年 11 月 5 日周四 18:12，小樱<notifications@github.com> 写道：   



这不应该看那里，而是应该看操作系统，我观察这个现象的方式是在一个root的安卓手机上使用adb shell安装busybox以后使用ss这个命令查看的。我打开了一个bilibili直播页面和一个淘宝页面，最多也就十几条。 等有时间我传个截图上来就明白了。 2020 年 11 月 5 日周四 17:33，小樱notifications@github.com 写道： 并不会发生你提到的现象，我实测了一下，每个页面一两百个请求最多也就十几条连接。再说了，shadowsocks从诞生以来也没有这个特性过，也没见那里报告过与此有关的性能问题。发热和耗电大多数情况下都是因为加密和连接方式的问题（例如websocket的方式就比纯连接耗电多），连接残留的话也不是什么问题，重新开关下对应的网络或者重开关下v2rayng的服务就没了。如果不去管那linux内核也会在超时时间后释放连接的。如果默认开了这个选项的话，会给更多普通用户带来极大的困扰，他们可能会想这软件怎么速度上和单纯的vpn没有区别？然后就会招来更多无意义的问题报告。 2020 年 11 月 5 日周四 17:19，小樱notifications@github.com 写道： @devinstever 你要知道，如果不开启的话，那么一个页面一两百个请求，就需要建立两百个tcp连接，握手200次，导致tcp握手响应时间严重拖慢速度，并且引起大量的tcp包请求导致性能问题，引起发热，功耗高等现象，并且不止手机客户端，服务器服务端也会导致大量的tcp包拥堵服务器引起死机等问题 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. 你这个是已经启用了mux，所以才会只有十几个请求连接，或者你访问的页面内容比较少，你可以通过f12抓包看页面具体的请求数量有多少 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.


你手机装个终端模拟器用ssh权限执行，或者服务器上用这个命令看一下就知道了
netstat -apn | grep v2ray

**Comment by 1265578519** [comment]
> 服务器上看到的并不准确，因为看到的连接总数是 客户端向代理服务程序的连接、代理服务程序向外的连接、服务器其他程序向外的连接加起来的。 发自 Android 版 Yahoo 邮箱 2020 年 11 月 5 日周四 18:12，小樱<notifications@github.com> 写道： 这不应该看那里，而是应该看操作系统，我观察这个现象的方式是在一个root的安卓手机上使用adb shell安装busybox以后使用ss这个命令查看的。我打开了一个bilibili直播页面和一个淘宝页面，最多也就十几条。 等有时间我传个截图上来就明白了。 2020 年 11 月 5 日周四 17:33，小樱notifications@github.com 写道： 并不会发生你提到的现象，我实测了一下，每个页面一两百个请求最多也就十几条连接。再说了，shadowsocks从诞生以来也没有这个特性过，也没见那里报告过与此有关的性能问题。发热和耗电大多数情况下都是因为加密和连接方式的问题（例如websocket的方式就比纯连接耗电多），连接残留的话也不是什么问题，重新开关下对应的网络或者重开关下v2rayng的服务就没了。如果不去管那linux内核也会在超时时间后释放连接的。如果默认开了这个选项的话，会给更多普通用户带来极大的困扰，他们可能会想这软件怎么速度上和单纯的vpn没有区别？然后就会招来更多无意义的问题报告。 2020 年 11 月 5 日周四 17:19，小樱notifications@github.com 写道： @devinstever 你要知道，如果不开启的话，那么一个页面一两百个请求，就需要建立两百个tcp连接，握手200次，导致tcp握手响应时间严重拖慢速度，并且引起大量的tcp包请求导致性能问题，引起发热，功耗高等现象，并且不止手机客户端，服务器服务端也会导致大量的tcp包拥堵服务器引起死机等问题 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. 你这个是已经启用了mux，所以才会只有十几个请求连接，或者你访问的页面内容比较少，你可以通过f12抓包看页面具体的请求数量有多少 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. 你手机装个终端模拟器用ssh权限执行，或者服务器上用这个命令看一下就知道了 netstat -apn | grep v2ray — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

你只用观察你客户端的ip就行了，没有启用mxu的情况下，到你客户端ip产生了多少个链接

**Comment by ghost** [comment]
客户端开启mux并不会减少代理服务端程序向外建立的连接，只会减少客户端向服务器建立的连接。（因为开网页的每一个请求都是真实的，到了出口这里对外连接的分配肯定是全部按真实情况来的）如果真的要为服务端减负的话，不能仅仅是开启这个就完了，还得结合其他的一些得当设定才行。
个人的看法是这样的：这个选项加上的确挺好的，同时也能满足部分特定需求。但是默认开启mux的话可能这个repository的主要开发者估计不会同意（因为使用它的人基本上还是要面对高延迟及丢包的环境的），如果不会同意的话作为协作者肯定也没有什么办法。所以看看最后会怎么说吧。 
 
  2020 年 11 月 6 日周五 0:40，小樱<notifications@github.com> 写道：   



服务器上看到的并不准确，因为看到的连接总数是 客户端向代理服务程序的连接、代理服务程序向外的连接、服务器其他程序向外的连接加起来的。 发自 Android 版 Yahoo 邮箱 2020 年 11 月 5 日周四 18:12，小樱notifications@github.com 写道： 这不应该看那里，而是应该看操作系统，我观察这个现象的方式是在一个root的安卓手机上使用adb shell安装busybox以后使用ss这个命令查看的。我打开了一个bilibili直播页面和一个淘宝页面，最多也就十几条。 等有时间我传个截图上来就明白了。 2020 年 11 月 5 日周四 17:33，小樱notifications@github.com 写道： 并不会发生你提到的现象，我实测了一下，每个页面一两百个请求最多也就十几条连接。再说了，shadowsocks从诞生以来也没有这个特性过，也没见那里报告过与此有关的性能问题。发热和耗电大多数情况下都是因为加密和连接方式的问题（例如websocket的方式就比纯连接耗电多），连接残留的话也不是什么问题，重新开关下对应的网络或者重开关下v2rayng的服务就没了。如果不去管那linux内核也会在超时时间后释放连接的。如果默认开了这个选项的话，会给更多普通用户带来极大的困扰，他们可能会想这软件怎么速度上和单纯的vpn没有区别？然后就会招来更多无意义的问题报告。 2020 年 11 月 5 日周四 17:19，小樱notifications@github.com 写道： @devinstever 你要知道，如果不开启的话，那么一个页面一两百个请求，就需要建立两百个tcp连接，握手200次，导致tcp握手响应时间严重拖慢速度，并且引起大量的tcp包请求导致性能问题，引起发热，功耗高等现象，并且不止手机客户端，服务器服务端也会导致大量的tcp包拥堵服务器引起死机等问题 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. 你这个是已经启用了mux，所以才会只有十几个请求连接，或者你访问的页面内容比较少，你可以通过f12抓包看页面具体的请求数量有多少 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. 你手机装个终端模拟器用ssh权限执行，或者服务器上用这个命令看一下就知道了 netstat -apn | grep v2ray — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.


你只用观察你客户端的ip就行了，没有启用mxu的情况下，到你客户端ip产生了多少个链接

**Comment by 1265578519** [comment]
> 客户端开启mux并不会减少代理服务端程序向外建立的连接，只会减少客户端向服务器建立的连接。（因为开网页的每一个请求都是真实的，到了出口这里对外连接的分配肯定是全部按真实情况来的）如果真的要为服务端减负的话，不能仅仅是开启这个就完了，还得结合其他的一些得当设定才行。 个人的看法是这样的：这个选项加上的确挺好的，同时也能满足部分特定需求。但是默认开启mux的话可能这个repository的主要开发者估计不会同意（因为使用它的人基本上还是要面对高延迟及丢包的环境的），如果不会同意的话作为协作者肯定也没有什么办法。所以看看最后会怎么说吧。 2020 年 11 月 6 日周五 0:40，小樱<notifications@github.com> 写道： 服务器上看到的并不准确，因为看到的连接总数是 客户端向代理服务程序的连接、代理服务程序向外的连接、服务器其他程序向外的连接加起来的。 发自 Android 版 Yahoo 邮箱 2020 年 11 月 5 日周四 18:12，小樱notifications@github.com 写道： 这不应该看那里，而是应该看操作系统，我观察这个现象的方式是在一个root的安卓手机上使用adb shell安装busybox以后使用ss这个命令查看的。我打开了一个bilibili直播页面和一个淘宝页面，最多也就十几条。 等有时间我传个截图上来就明白了。 2020 年 11 月 5 日周四 17:33，小樱notifications@github.com 写道： 并不会发生你提到的现象，我实测了一下，每个页面一两百个请求最多也就十几条连接。再说了，shadowsocks从诞生以来也没有这个特性过，也没见那里报告过与此有关的性能问题。发热和耗电大多数情况下都是因为加密和连接方式的问题（例如websocket的方式就比纯连接耗电多），连接残留的话也不是什么问题，重新开关下对应的网络或者重开关下v2rayng的服务就没了。如果不去管那linux内核也会在超时时间后释放连接的。如果默认开了这个选项的话，会给更多普通用户带来极大的困扰，他们可能会想这软件怎么速度上和单纯的vpn没有区别？然后就会招来更多无意义的问题报告。 2020 年 11 月 5 日周四 17:19，小樱notifications@github.com 写道： @devinstever 你要知道，如果不开启的话，那么一个页面一两百个请求，就需要建立两百个tcp连接，握手200次，导致tcp握手响应时间严重拖慢速度，并且引起大量的tcp包请求导致性能问题，引起发热，功耗高等现象，并且不止手机客户端，服务器服务端也会导致大量的tcp包拥堵服务器引起死机等问题 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. 你这个是已经启用了mux，所以才会只有十几个请求连接，或者你访问的页面内容比较少，你可以通过f12抓包看页面具体的请求数量有多少 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. 你手机装个终端模拟器用ssh权限执行，或者服务器上用这个命令看一下就知道了 netstat -apn | grep v2ray — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. 你只用观察你客户端的ip就行了，没有启用mxu的情况下，到你客户端ip产生了多少个链接 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

嗯，等开发者来看怎么搞吧，毕竟缺少mux，客户机会费电浪费性能，都可以看到很多人说费电发烫的反映帖子。就是没有启用这个mux功能引起的
而且手机反复建立握手连接会增加延迟影响打开页面的速度，实在是拉胯网速，个人认为最好是同步PC客户端的做法，默认开启该功能
